[tools]
bat = "latest"
btop = "1.4.4"
chezmoi = "latest"
fd = "10.2.0"
fzf = "0.62.0"
github-cli = "2.82.1"
k9s = "latest"
kubelogin = "latest"
lsd = "latest"
lazygit = "latest"
kubectl = "latest"
neovim = "0.11.5"
omnictl = "latest"
ripgrep = "14.1.1"
starship = "1.24.1"
talosctl = "latest"

[env]
GITHUB_TOKEN = "{{ exec(command='gh auth token') }}"
