[tools]
bat = "latest"
btop = "1.4.4"
chezmoi = "latest"
fd = "10.2.0"
fzf = "0.62.0"
github-cli = "2.82.1"
lsd = "latest"
lazygit = "latest"
neovim = "0.11.5"
omnictl = "latest"
ripgrep = "14.1.1"
starship = "1.24.1"
python = "3.14"
